config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='courses:courses')),
    path('users/', include('user.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CoursesView.as_view(), name='courses'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('create/', views.CreatCourseView.as_view(), name='course-create'),
    path('delete/<slug:slug>/', views.CourseDeleteView.as_view(), name='course-delete'),
    path('edit/<slug:slug>/', views.CourseUpdateView.as_view(), name='course-edit'),
]

user/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

app_name = 'user'

urlpatterns = [
    path('registration/', views.registration_view, name="registration"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),

    # path('', lambda x: HttpResponse('thank you'), name='home')
]

templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'user:login' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          {% if user.is_authenticated %}
              <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'user:logout' %}">Log out</a>
          </li>
              <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="">{{ user }}</a>
          </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:registration' %}">Registration</a>
              </li>
          {% endif %}
<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'courses:courses' %}">Courses</a>
        </li>

      {% if user.is_authenticated %}
                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'courses:course-create' %}">Add course</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>