config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='courses:courses')),
    path('users/', include('user.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CoursesView.as_view(), name='courses'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('create/', views.CreatCourseView.as_view(), name='course-create'),
    path('delete/<slug:slug>/', views.CourseDeleteView.as_view(), name='course-delete'),
    path('edit/<slug:slug>/', views.CourseUpdateView.as_view(), name='course-edit'),
]

user/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

app_name = 'user'

urlpatterns = [
    path('registration/', views.registration_view, name="registration"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),

    # path('', lambda x: HttpResponse('thank you'), name='home')
]

courses/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template.loader import render_to_string
from django.utils.text import slugify

from courses.fields import OrderField


class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Course(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='courses_creator')
    title = models.CharField(max_length=200)
    subject = models.ForeignKey('Subject', related_name='courses', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(get_user_model(), related_name='courses_students', blank=True)
    course_image = models.ImageField(upload_to='images', null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)


class Module(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, default='')
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='modules')
    order = OrderField(blank=True, for_fields=['course'])

    def __str__(self):
        return f'{self.order}. {self.title}'

    class Meta:
        ordering = ['order']


class Content(models.Model):
    module = models.ForeignKey('Module', related_name='contents', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={
        'model__in': ('text', 'video', 'image', 'file')
        })
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(get_user_model(), related_name='%(class)s_related', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True

    def render(self):
        return render_to_string(f'courses/contents/{self._meta.model_name}.html', {'item': self})


class Text(ItemBase):
    content = models.TextField()


class File(ItemBase):
    content = models.FileField(upload_to='files')


class Image(ItemBase):
    content = models.ImageField(upload_to='content_images')


class Video(ItemBase):
    content = models.URLField()

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from . import models
from .permissions import AuthorManageMixin


class CoursesView(ListView):
    model = models.Course
    template_name = 'courses/courses_list.html'
    context_object_name = 'courses'


class CourseDetailView(DetailView):
    model = models.Course
    template_name = 'courses/course_page.html'
    context_object_name = 'course'


class CreatCourseView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Course
    fields = ('title', 'subject', 'slug', 'overview', 'course_image')
    template_name = 'courses/create_course.html'
    login_url = reverse_lazy('user:login')
    success_url = reverse_lazy('courses:courses')
    permission_required = 'courses.add_course'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CourseDeleteView(LoginRequiredMixin, PermissionRequiredMixin, AuthorManageMixin, DeleteView):
    model = models.Course
    template_name = 'courses/delete_course.html'
    success_url = reverse_lazy('courses:courses')
    permission_required = 'courses.delete_course'
    login_url = reverse_lazy('user:login')
    context_object_name = 'course'


class CourseUpdateView(LoginRequiredMixin, PermissionRequiredMixin, AuthorManageMixin, UpdateView):
    model = models.Course
    fields = ('title', 'subject', 'overview', 'slug', 'course_image')
    template_name = 'courses/update_course.html'
    login_url = reverse_lazy('user:login')
    success_url = reverse_lazy('courses:courses')
    permission_required = 'courses.change_course'
    context_object_name = 'course'

courses/templates/courses/course_page.html
{% extends 'base.html' %}

{% block container %}
    <div class="row">
        <div class="col-md-3 col-md-offset-2">
            <img src="{{ course.course_image.url }}" alt="{{ course.title }}" class="img-thumbnail">
        </div>
        <div class="col-md-9">
            <h1>{{ course.title }}</h1>
            <p><i>Created by: {{ course.owner.fullname }} at {{ course.created|date }}</i></p>
            <p class="lead my-3">{{ course.overview }}</p>
            {% if user.is_authenticated %}
                {% if user.id == course.owner.id %}
                    <p class="lead mb-0 btn-group-sm">
                        <a href="{% url 'courses:course-edit' slug=course.slug %}" class="btn btn-danger">Edit course</a>
                        <a href="{% url 'courses:course-delete' slug=course.slug %}" class="btn btn-danger">Delete course</a>
                        <a href="" class="btn btn-danger">Edit modules</a>
                    </p>
                {% else %}
                    <p class="lead mb-0 btn-group-sm">
                        {% if not user in course.students.all %}
                            <form action="" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger float-end ml-2" value="Take this course">
                            </form>
                        {% else %}
                            <a href="" class="btn btn-success">View course</a>
                        {% endif %}
                    </p>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            {% if course.modules.count %}
                <h2>{{ course.title }}`s Modules</h2>
                <hr>
                <ul class="nav nav-pills flex-column">
                    <div class="accordion" id="accordionExample">
                        {% for module in course.modules.all %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button {% if not forloop.first %}collapsed{% endif %}" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#collapse{{ module.order }}" aria-expanded="{% if forloop.first %}true {% else %} false{% endif %}"
                                            aria-controls="collapseOne">
                                        {{ module.title }}
                                    </button>
                                </h2>
                                <div id="collapse{{ module.order }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}"
                                     aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        {{ module.description }}
                                        <hr>
                                        {% if user.is_authenticated %}
                                            {% for content in module.contents.all %}
                                                {{ content.item.render }}
                                            {% endfor %}

                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

courses/templates/courses/courses_list.html
{% extends 'base.html' %}

{% block container %}

    <div class="row">
        <div class="col">
            <div class="card-group">
                {% for course in courses %}
                    <div class="card mb-3 me-3" style="max-width: 18rem;">
                        <img src="{{ course.course_image.url }}" alt="{{ course.title }}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.title }}</h5>
                            <p class="card-text">{{ course.overview }}</p>
                            <a href="{% url 'courses:course-detail' pk=course.pk %}" class="btn btn-primary">See course</a></div>
                    </div>
                    {% empty %}
                    <h2>No courses found.</h2>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}

courses/templates/courses/create_course.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block container %}

    <form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    <h3 class="text-center mt-3">Add a new course</h3>
        {% if form.errors %}
        {{ form.errors }}
        {% endif %}
    {{ form|crispy }}
        <button class="btn btn-success float-end btn-lg mb-3 mt-0" type="submit">Add course</button>

    </form>

{% endblock %}

courses/templates/courses/delete_course.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block container %}

    <form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
        <h2 class="text-center mt-3">Are you sure you want to delete <b>{{ course }}</b></h2>
        <button class="btn btn-danger float-end btn-lg mb-3 mt-0" type="submit">Confirm</button>

    </form>

{% endblock %}

courses/templates/courses/update_course.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block container %}

    <form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    <h3 class="text-center mt-3">Editing course: {{ course }}</h3>
        {% if form.errors %}
        {{ form.errors }}
        {% endif %}
    {{ form|crispy }}
        <button class="btn btn-success float-end btn-lg mb-3 mt-0" type="submit">Update course</button>

    </form>

{% endblock %}